import type { Plugin } from 'vue';
import Button from './components/Button.vue';
import Card from './components/Card.vue';
import Badge from './components/Badge.vue';
import Divider from './components/Divider.vue';
import Input from './components/Input.vue';
import Textarea from './components/Textarea.vue';
import Checkbox from './components/Checkbox.vue';
import Radio from './components/Radio.vue';
import Switch from './components/Switch.vue';
import Select from './components/Select.vue';
import Pagination from './components/Pagination.vue';
import Modal from './components/Modal.vue';
import Toast from './components/Toast.vue';
import Tabs from './components/Tabs.vue';
import Skeleton from './components/Skeleton.vue';
import Tooltip from './components/Tooltip.vue';
import { useToast } from './composables/useToast';
import './styles/index.css';
export declare const install: Plugin;
export { Button, Card, Badge, Divider, Input, Textarea, Checkbox, Radio, Switch, Select, Pagination, Modal, Toast, Tabs, Skeleton, Tooltip, useToast, };
